
export const GET_CATEGORIES = 'GET_CATEGORIES';

export const POSTS_LOADED = 'POST_LOADED';
export const POSTS_SEARCHED_BY_CATEGORY = 'POSTS_SEARCHED_BY_CATEGORY';
export const POSTS_SEARCHED = 'POST_SEARCHED';
export const POST_VOTED = 'POST_VOTED';
export const POST_CREATED = 'POST_CREATED';

export const GET_COMMENTS_POST = 'GET_COMMENTS_POST';
export const COMMENT_VOTED = 'COMMENT_VOTED';
export const GET_COMMENT = 'GET_COMMENT';


