
export const GET_CATEGORIES = 'GET_CATEGORIES';

export const POST_LOADED = 'POST_LOADED';
export const POST_UPDATED = 'POST_UPDATED';
export const POSTS_SEARCHED_BY_CATEGORY = 'POSTS_SEARCHED_BY_CATEGORY';
export const POSTS_SEARCHED = 'POST_SEARCHED';
export const POST_VOTED = 'POST_VOTED';
export const POST_CREATED = 'POST_CREATED';

export const GET_COMMENTS_POST = 'GET_COMMENTS_POST';
export const COMMENT_VOTED = 'COMMENT_VOTED';
export const GET_COMMENT = 'GET_COMMENT';
export const ADD_COMMENT = 'ADD_COMMENT';
export const REMOVE_COMMENT = 'REMOVE_COMMENT';
export const EDIT_COMMENT = 'EDIT_COMMENT';
export const UPDATE_COMMENT = 'UPDATE_COMMENT';
export const OPEN_MODAL = 'OPEN_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';

export const OPEN_SIDE_MENU = 'OPEN_SIDE_MENU';
export const CLOSE_SIDE_MENU = 'CLOSE_SIDE_MENU';


